### PR TITLE
Update versions; misc tidy ups

### PR DESCRIPTION
**Pull request by richdougherty**
- Added "seed" tag to template
- Remove Activator shims
- Remove snapshot repository
- Use secure dev mode application.secret
- Added .gitignore

### CODE REVIEW

**Comment by loicdescotte** [comment]
Thanks!

**Comment by richdougherty** [comment]
No worries! If you get a chance would you be able to publish the template to the [Activator site](https://typesafe.com/activator/template/play-slick-quickstart)?

**Comment by loicdescotte** [comment]
Hi,
Yes, no problem, I'm doing it right now!

**Comment by richdougherty** [comment]
Great, thanks!

**Pull request merged**
